name: Deploy website

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write

env:
  RUST_BACKTRACE: 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: devenv

      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest
        shell: sh

      - name: Build website
        run: devenv shell wasm-pack build --release && cd www && yarn install --frozen-lockfile && yarn run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www/dist
